"""add communication and import tables

Revision ID: d45b6b640e68
Revises: 57f7ae97bf3c
Create Date: 2026-08-08 17:27:02.896329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd45b6b640e68'
down_revision: Union[str, None] = '57f7ae97bf3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communication_drafts',
    sa.Column('draft_id', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('order_no', sa.String(), nullable=True),
    sa.Column('draft_type', sa.String(), nullable=False),
    sa.Column('recipient_role', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('ai_subject', sa.String(), nullable=True),
    sa.Column('ai_draft', sa.Text(), nullable=True),
    sa.Column('edited_subject', sa.String(), nullable=True),
    sa.Column('edited_draft', sa.Text(), nullable=True),
    sa.Column('final_text', sa.Text(), nullable=True),
    sa.Column('facts_used_json', sa.Text(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('missing_facts_json', sa.Text(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('questions_to_ask_json', sa.Text(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('risk_flags_json', sa.Text(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('run_status', sa.String(), nullable=False),
    sa.Column('approval_status', sa.String(), nullable=True),
    sa.Column('human_status', sa.String(), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('reviewer_id', sa.String(), nullable=True),
    sa.Column('review_note', sa.String(), nullable=True),
    sa.Column('approved_at', sa.String(), nullable=True),
    sa.Column('copied_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('draft_id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index('idx_comm_drafts_order', 'communication_drafts', ['order_id', 'order_no'], unique=False)
    op.create_index('idx_comm_drafts_status', 'communication_drafts', ['human_status', 'run_status'], unique=False)
    op.create_table('communication_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('operator_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('idx_comm_events_entity', 'communication_events', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_table('communication_task_candidates',
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('source_message_id', sa.String(), nullable=True),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('order_no', sa.String(), nullable=True),
    sa.Column('communication_text', sa.String(), nullable=False),
    sa.Column('sender_role', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('task_candidate_json', sa.Text(), nullable=False),
    sa.Column('run_status', sa.String(), nullable=False),
    sa.Column('review_status', sa.String(), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('reviewer_id', sa.String(), nullable=True),
    sa.Column('review_note', sa.String(), nullable=True),
    sa.Column('ft03_result_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('reviewed_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('candidate_id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index('idx_comm_candidates_order', 'communication_task_candidates', ['order_id', 'order_no'], unique=False)
    op.create_index('idx_comm_candidates_status', 'communication_task_candidates', ['review_status', 'run_status'], unique=False)
    op.create_table('communication_workflow_runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('workflow_code', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('input_json', sa.Text(), nullable=False),
    sa.Column('output_json', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('debug_url', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index('idx_comm_runs_workflow', 'communication_workflow_runs', ['workflow_code', 'created_at'], unique=False)
    op.create_table('order_import_batches',
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('source_filename', sa.String(), nullable=False),
    sa.Column('source_sha256', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('total_rows', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('importable_rows', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_rows', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('mapping_json', sa.Text(), nullable=False),
    sa.Column('summary_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('committed_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_table('order_import_rows',
    sa.Column('row_id', sa.String(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.Column('normalized_json', sa.Text(), nullable=False),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('issues_json', sa.Text(), nullable=False),
    sa.Column('changes_json', sa.Text(), nullable=False),
    sa.Column('existing_order_id', sa.String(), nullable=True),
    sa.Column('commit_status', sa.String(), nullable=True),
    sa.Column('commit_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['order_import_batches.batch_id'], ),
    sa.PrimaryKeyConstraint('row_id')
    )
    op.create_index('idx_order_import_rows_batch', 'order_import_rows', ['batch_id'], unique=False)
    op.create_index('idx_order_import_rows_classification', 'order_import_rows', ['classification'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_order_import_rows_classification', table_name='order_import_rows')
    op.drop_index('idx_order_import_rows_batch', table_name='order_import_rows')
    op.drop_table('order_import_rows')
    op.drop_table('order_import_batches')
    op.drop_index('idx_comm_runs_workflow', table_name='communication_workflow_runs')
    op.drop_table('communication_workflow_runs')
    op.drop_index('idx_comm_candidates_status', table_name='communication_task_candidates')
    op.drop_index('idx_comm_candidates_order', table_name='communication_task_candidates')
    op.drop_table('communication_task_candidates')
    op.drop_index('idx_comm_events_entity', table_name='communication_events')
    op.drop_table('communication_events')
    op.drop_index('idx_comm_drafts_status', table_name='communication_drafts')
    op.drop_index('idx_comm_drafts_order', table_name='communication_drafts')
    op.drop_table('communication_drafts')
    # ### end Alembic commands ###
