"""initial schema

Revision ID: 57f7ae97bf3c
Revises: 
Create Date: 2026-08-08 17:10:55.431993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57f7ae97bf3c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_chat_jobs',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), server_default=sa.text("'ORG-DEMO'"), nullable=False),
    sa.Column('current_user_id', sa.String(), nullable=False),
    sa.Column('current_role', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'QUEUED'"), nullable=False),
    sa.Column('request_json', sa.Text(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('linked_run_id', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('started_at', sa.String(), nullable=True),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index('idx_agent_chat_jobs_user_status', 'agent_chat_jobs', ['current_user_id', 'status', 'created_at'], unique=False)
    op.create_table('agent_runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), server_default=sa.text("'ORG-DEMO'"), nullable=False),
    sa.Column('current_user_id', sa.String(), nullable=False),
    sa.Column('current_role', sa.String(), nullable=False),
    sa.Column('goal', sa.String(), nullable=False),
    sa.Column('trigger_type', sa.String(), server_default=sa.text("'USER'"), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('max_tool_calls', sa.Integer(), server_default=sa.text('8'), nullable=False),
    sa.Column('max_duration_seconds', sa.Integer(), server_default=sa.text('60'), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('stop_reason', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.String(), nullable=True),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index('idx_agent_runs_user_time', 'agent_runs', ['current_user_id', sa.text('created_at DESC')], unique=False)
    op.create_table('analytics_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('user_role', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), server_default=sa.text("'server'"), nullable=False),
    sa.Column('app_version', sa.String(), server_default=sa.text("'6.1.0'"), nullable=False),
    sa.Column('properties_json', sa.Text(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('client_timestamp', sa.String(), nullable=True),
    sa.Column('server_timestamp', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('idx_analytics_event_time', 'analytics_events', ['event_name', sa.text('server_timestamp DESC')], unique=False)
    op.create_index('idx_analytics_order', 'analytics_events', ['order_id', sa.text('server_timestamp DESC')], unique=False)
    op.create_index('idx_analytics_run', 'analytics_events', ['run_id', sa.text('server_timestamp DESC')], unique=False)
    op.create_index('idx_analytics_user_time', 'analytics_events', ['user_id', sa.text('server_timestamp DESC')], unique=False)
    op.create_table('bulk_update_batches',
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), server_default=sa.text("'ORG-DEMO'"), nullable=False),
    sa.Column('current_user_id', sa.String(), nullable=False),
    sa.Column('current_role', sa.String(), nullable=False),
    sa.Column('source_text', sa.String(), nullable=False),
    sa.Column('parser_mode', sa.String(), server_default=sa.text("'hybrid_rules_v1'"), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'PARSED'"), nullable=False),
    sa.Column('summary_json', sa.Text(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('confirmed_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_table('confirmation_snapshots',
    sa.Column('confirmation_id', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('operator_id', sa.String(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('confirmation_id')
    )
    op.create_table('event_logs',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('operator_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('idx_events_entity', 'event_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('idempotency_records',
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('result_status', sa.String(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('idempotency_key')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('order_no', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('packaging_method', sa.String(), nullable=True),
    sa.Column('requested_delivery_date', sa.String(), nullable=True),
    sa.Column('latest_supplier_commitment', sa.String(), nullable=True),
    sa.Column('current_progress', sa.Float(), nullable=True),
    sa.Column('current_node', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('action_readiness', sa.String(), server_default=sa.text("'BASE_ONLY'"), nullable=False),
    sa.Column('contact_status', sa.String(), server_default=sa.text("'UNKNOWN'"), nullable=False),
    sa.Column('issue_status', sa.String(), server_default=sa.text("'UNKNOWN'"), nullable=False),
    sa.Column('initialization_waiting_on', sa.String(), nullable=True),
    sa.Column('initialization_promised_reply_at', sa.String(), nullable=True),
    sa.Column('initialization_note', sa.String(), nullable=True),
    sa.Column('initialization_source', sa.String(), nullable=True),
    sa.Column('initialized_at', sa.String(), nullable=True),
    sa.Column('last_dynamic_update_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('order_id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_index('idx_orders_action_readiness', 'orders', ['action_readiness', 'requested_delivery_date'], unique=False)
    op.create_index('idx_orders_owner', 'orders', ['owner'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('settings_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('workflow_runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('workflow_key', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('input_json', sa.Text(), nullable=False),
    sa.Column('output_json', sa.Text(), nullable=True),
    sa.Column('coze_code', sa.Integer(), nullable=True),
    sa.Column('coze_msg', sa.String(), nullable=True),
    sa.Column('debug_url', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index('idx_workflow_runs_key_time', 'workflow_runs', ['workflow_key', 'created_at'], unique=False)
    op.create_table('agent_tool_calls',
    sa.Column('call_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('request_json', sa.Text(), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.run_id'], ),
    sa.PrimaryKeyConstraint('call_id')
    )
    op.create_index('idx_agent_calls_run_time', 'agent_tool_calls', ['run_id', 'created_at'], unique=False)
    op.create_table('anomaly_candidates',
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('anomaly_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('score', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('evidence_json', sa.Text(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('missing_information_json', sa.Text(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('recommended_action', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default=sa.text("'ANOMALY_CANDIDATE'"), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('confirmed_by', sa.String(), nullable=True),
    sa.Column('confirmed_at', sa.String(), nullable=True),
    sa.Column('resolution_note', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.run_id'], ),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    op.create_index('idx_anomalies_order_status', 'anomaly_candidates', ['order_id', 'status', 'severity'], unique=False)
    op.create_table('bulk_update_candidates',
    sa.Column('update_id', sa.String(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('order_no', sa.String(), nullable=True),
    sa.Column('source_segment', sa.String(), nullable=False),
    sa.Column('match_confidence', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('old_value_json', sa.Text(), nullable=True),
    sa.Column('new_value_json', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('risk_level', sa.String(), server_default=sa.text("'normal'"), nullable=False),
    sa.Column('requires_approval', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('edited_value_json', sa.Text(), nullable=True),
    sa.Column('approval_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('decided_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['bulk_update_batches.batch_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('update_id')
    )
    op.create_index('idx_bulk_update_batch_status', 'bulk_update_candidates', ['batch_id', 'status'], unique=False)
    op.create_index('idx_bulk_update_order', 'bulk_update_candidates', ['order_id', sa.text('created_at DESC')], unique=False)
    op.create_table('daily_inspection_reports',
    sa.Column('report_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), server_default=sa.text("'ORG-DEMO'"), nullable=False),
    sa.Column('current_user_id', sa.String(), nullable=False),
    sa.Column('inspection_date', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), server_default=sa.text("'Asia/Shanghai'"), nullable=False),
    sa.Column('scope_json', sa.Text(), nullable=False),
    sa.Column('report_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.run_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index('idx_reports_user_date', 'daily_inspection_reports', ['current_user_id', sa.text('inspection_date DESC')], unique=False)
    op.create_table('intake_jobs',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('workflow_key', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('request_json', sa.Text(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('error_json', sa.Text(), nullable=True),
    sa.Column('review_id', sa.String(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('progress_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('started_at', sa.String(), nullable=True),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index('idx_intake_jobs_status_time', 'intake_jobs', ['status', 'created_at'], unique=False)
    op.create_table('logistics_events',
    sa.Column('logistics_event_id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('event_time', sa.String(), nullable=True),
    sa.Column('estimated_arrival_at', sa.String(), nullable=True),
    sa.Column('source', sa.String(), server_default=sa.text("'SYNTHETIC_OR_MANUAL'"), nullable=False),
    sa.Column('resolved_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('logistics_event_id')
    )
    op.create_index('idx_logistics_order_status', 'logistics_events', ['order_id', 'status', 'event_time'], unique=False)
    op.create_table('order_dependencies',
    sa.Column('dependency_id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('dependency_type', sa.String(), nullable=False),
    sa.Column('dependency_name', sa.String(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('blocking_party', sa.String(), nullable=True),
    sa.Column('due_at', sa.String(), nullable=True),
    sa.Column('evidence_json', sa.Text(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('dependency_id')
    )
    op.create_index('idx_dependencies_order_status', 'order_dependencies', ['order_id', 'status'], unique=False)
    op.create_table('source_messages',
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('source_channel', sa.String(), nullable=False),
    sa.Column('sender_role', sa.String(), nullable=False),
    sa.Column('message_type', sa.String(), nullable=True),
    sa.Column('raw_content', sa.String(), nullable=False),
    sa.Column('source_time', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('approval_requests',
    sa.Column('approval_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('candidate_id', sa.String(), nullable=True),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('requested_by', sa.String(), nullable=False),
    sa.Column('required_role', sa.String(), server_default=sa.text("'operator_or_manager'"), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('decided_by', sa.String(), nullable=True),
    sa.Column('decision_note', sa.String(), nullable=True),
    sa.Column('decided_at', sa.String(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['anomaly_candidates.candidate_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.run_id'], ),
    sa.PrimaryKeyConstraint('approval_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('idx_approvals_status_role', 'approval_requests', ['status', 'required_role', 'created_at'], unique=False)
    op.create_table('candidate_reviews',
    sa.Column('review_id', sa.String(), nullable=False),
    sa.Column('source_message_id', sa.String(), nullable=True),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('workflow_source', sa.String(), server_default=sa.text("'LOCAL_RULE_DEMO'"), nullable=False),
    sa.Column('candidate_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('reviewer_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('reviewed_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['source_message_id'], ['source_messages.message_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index('idx_reviews_order', 'candidate_reviews', ['order_id'], unique=False)
    op.create_index('idx_reviews_status', 'candidate_reviews', ['status', 'created_at'], unique=False)
    op.create_table('commitment_history',
    sa.Column('commitment_id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('commitment_type', sa.String(), nullable=False),
    sa.Column('commitment_value', sa.String(), nullable=False),
    sa.Column('source_message_id', sa.String(), nullable=True),
    sa.Column('confirmed_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['source_message_id'], ['source_messages.message_id'], ),
    sa.PrimaryKeyConstraint('commitment_id')
    )
    op.create_table('tasks',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('related_order_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('recommended_action', sa.String(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default=sa.text("'OPEN'"), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=True),
    sa.Column('responsibility_status', sa.String(), server_default=sa.text("'assigned'"), nullable=False),
    sa.Column('waiting_on', sa.String(), nullable=True),
    sa.Column('promised_reply_at', sa.String(), nullable=True),
    sa.Column('next_action_at', sa.String(), nullable=True),
    sa.Column('business_deadline', sa.String(), nullable=True),
    sa.Column('last_contact_at', sa.String(), nullable=True),
    sa.Column('risk_level', sa.String(), server_default=sa.text("'none'"), nullable=False),
    sa.Column('urgent', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('pending_confirmation', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('source_message_id', sa.String(), nullable=True),
    sa.Column('evidence_json', sa.Text(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['related_order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['source_message_id'], ['source_messages.message_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index('idx_tasks_order', 'tasks', ['related_order_id'], unique=False)
    op.create_index('idx_tasks_owner', 'tasks', ['owner_user_id'], unique=False)
    op.create_index('idx_tasks_waiting', 'tasks', ['waiting_on', 'promised_reply_at'], unique=False)
    op.create_table('risk_signals',
    sa.Column('risk_id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('risk_type', sa.String(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('evidence', sa.String(), nullable=True),
    sa.Column('rule_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default=sa.text("'OPEN'"), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.PrimaryKeyConstraint('risk_id')
    )
    op.create_index('idx_risks_order', 'risk_signals', ['order_id'], unique=False)
    op.create_table('task_rankings',
    sa.Column('current_user_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('action_state', sa.String(), nullable=False),
    sa.Column('recommended_action', sa.String(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('next_action_at', sa.String(), nullable=True),
    sa.Column('ranking_suppressed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('priority_score', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('priority_reasons_json', sa.Text(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('evidence_json', sa.Text(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('workflow_run_id', sa.String(), nullable=True),
    sa.Column('calculated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.run_id'], ),
    sa.PrimaryKeyConstraint('current_user_id', 'task_id')
    )
    op.create_index('idx_rankings_user_score', 'task_rankings', ['current_user_id', sa.text('priority_score DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_rankings_user_score', table_name='task_rankings')
    op.drop_table('task_rankings')
    op.drop_index('idx_risks_order', table_name='risk_signals')
    op.drop_table('risk_signals')
    op.drop_index('idx_tasks_waiting', table_name='tasks')
    op.drop_index('idx_tasks_owner', table_name='tasks')
    op.drop_index('idx_tasks_order', table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('commitment_history')
    op.drop_index('idx_reviews_status', table_name='candidate_reviews')
    op.drop_index('idx_reviews_order', table_name='candidate_reviews')
    op.drop_table('candidate_reviews')
    op.drop_index('idx_approvals_status_role', table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_table('source_messages')
    op.drop_index('idx_dependencies_order_status', table_name='order_dependencies')
    op.drop_table('order_dependencies')
    op.drop_index('idx_logistics_order_status', table_name='logistics_events')
    op.drop_table('logistics_events')
    op.drop_index('idx_intake_jobs_status_time', table_name='intake_jobs')
    op.drop_table('intake_jobs')
    op.drop_index('idx_reports_user_date', table_name='daily_inspection_reports')
    op.drop_table('daily_inspection_reports')
    op.drop_index('idx_bulk_update_order', table_name='bulk_update_candidates')
    op.drop_index('idx_bulk_update_batch_status', table_name='bulk_update_candidates')
    op.drop_table('bulk_update_candidates')
    op.drop_index('idx_anomalies_order_status', table_name='anomaly_candidates')
    op.drop_table('anomaly_candidates')
    op.drop_index('idx_agent_calls_run_time', table_name='agent_tool_calls')
    op.drop_table('agent_tool_calls')
    op.drop_index('idx_workflow_runs_key_time', table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_table('user_settings')
    op.drop_index('idx_orders_owner', table_name='orders')
    op.drop_index('idx_orders_action_readiness', table_name='orders')
    op.drop_table('orders')
    op.drop_table('idempotency_records')
    op.drop_index('idx_events_entity', table_name='event_logs')
    op.drop_table('event_logs')
    op.drop_table('confirmation_snapshots')
    op.drop_table('bulk_update_batches')
    op.drop_index('idx_analytics_user_time', table_name='analytics_events')
    op.drop_index('idx_analytics_run', table_name='analytics_events')
    op.drop_index('idx_analytics_order', table_name='analytics_events')
    op.drop_index('idx_analytics_event_time', table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_index('idx_agent_runs_user_time', table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index('idx_agent_chat_jobs_user_status', table_name='agent_chat_jobs')
    op.drop_table('agent_chat_jobs')
    # ### end Alembic commands ###
